version: "3.4"
services:
    mongo:
        build: .
        container_name: mongo
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_USER=metauser
            - MONGO_PASSWORD=metauser
            - MONGO_DB=meta-commerce
    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/meta-commerce
        depends_on:
            - mongo